# -*- coding: utf-8 -*-
"""BD parte 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPHMD2tvLY7Zq_zzIKuKQ3hwhCBP0Wip
"""

import sqlite3

def crear_db():
    conn = sqlite3.connect('estudiante.db')
    c = conn.cursor()
    c.execute("""
    CREATE TABLE IF NOT EXISTS estudiante (
        Nombre TEXT,
        Edad INTEGER,
        Carrera TEXT,
        Matricula TEXT PRIMARY KEY
    )
    """)
    conn.commit()
    return conn, c

def insertar_estudiante(conn, c, nombre, edad, carrera, matricula):
    c.execute("INSERT OR REPLACE INTO estudiante (Nombre, Edad, Carrera, Matricula) VALUES (?, ?, ?, ?)",
              (nombre, edad, carrera, matricula))
    conn.commit()
    print(f"Estudiante {nombre} insertado correctamente.")

def modificar_estudiante(conn, c, matricula, nombre=None, edad=None, carrera=None):
    c.execute("SELECT * FROM estudiante WHERE Matricula = ?", (matricula,))
    registro = c.fetchone()

    if registro:
        nombre = nombre if nombre else registro[0]
        edad = edad if edad else registro[1]
        carrera = carrera if carrera else registro[2]

        c.execute("""
            UPDATE estudiante
            SET Nombre = ?, Edad = ?, Carrera = ?
            WHERE Matricula = ?
        """, (nombre, edad, carrera, matricula))
        conn.commit()
        print(f"Estudiante con matrícula {matricula} modificado correctamente.")
    else:
        print(f"No se encontró estudiante con matrícula {matricula}.")

def eliminar_estudiante(conn, c, matricula):
    c.execute("DELETE FROM estudiante WHERE Matricula = ?", (matricula,))
    conn.commit()
    print(f"Estudiante con matrícula {matricula} eliminado correctamente.")

def mostrar_estudiantes(c):
    print("\nLista de estudiantes:")
    c.execute("SELECT * FROM estudiante")
    registros = c.fetchall()

    if registros:
        for r in registros:
            print(f"Nombre: {r[0]}, Edad: {r[1]}, Carrera: {r[2]}, Matrícula: {r[3]}")
    else:
        print("No hay estudiantes registrados.")

conn, c = crear_db()

insertar_estudiante(conn, c, "Jesus", 17, "CDIA", "231690263-0")

modificar_estudiante(conn, c, "231690263-0", nombre="Jesus Ricardo", edad=18)

eliminar_estudiante(conn, c, "231690263-0")

mostrar_estudiantes(c)

conn.close()