# -*- coding: utf-8 -*-
"""Crear BD 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ac3920L1vtY1mCJpiszBlI9q4Nbm6Cz6
"""

import sqlite3

def crear_db():
    conn = sqlite3.connect('estudiante.db')
    c = conn.cursor()
    c.execute("""
    CREATE TABLE IF NOT EXISTS estudiante (
        Nombre TEXT,
        Edad INTEGER,
        Carrera TEXT,
        Matricula TEXT
    )
    """)
    conn.commit()
    return conn, c

def insertar_estudiante(conn, c, nombre, edad, carrera, matricula):
    c.execute("INSERT INTO estudiante (Nombre, Edad, Carrera, Matricula) VALUES (?, ?, ?, ?)",
              (nombre, edad, carrera, matricula))
    conn.commit()
    print(f"Estudiante {nombre} insertado correctamente.")

def mostrar_estudiantes(c):
    print("\nLista de estudiantes:")
    c.execute("SELECT * FROM estudiante")
    registros = c.fetchall()

    if registros:
        for r in registros:
            print(f"Nombre: {r[0]}, Edad: {r[1]}, Carrera: {r[2]}, Matrícula: {r[3]}")


mostrar_estudiantes(c)
conn.close()