# -*- coding: utf-8 -*-
"""Crear BD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ac3920L1vtY1mCJpiszBlI9q4Nbm6Cz6
"""

import sqlite3

conn = sqlite3.connect('estudiante.db')
c = conn.cursor()

c.execute("""
CREATE TABLE IF NOT EXISTS estudiante (
    Nombre TEXT,
    Edad INTEGER,
    Carrera TEXT,
    Matricula TEXT
)
""")


c.execute("INSERT INTO estudiante (Nombre, Edad, Carrera, Matricula) VALUES (?, ?, ?, ?)",
          ("Jesus", 17, "CDIA", "231690263-0"))

c.execute("SELECT * FROM estudiante")
registros = c.fetchall()

print(" Lista de estudiantes ")
for r in registros:
    print(f"Nombre: {r[0]}, Edad: {r[1]}, Carrera: {r[2]}, Matrícula: {r[3]}")


conn.commit()
conn.close()