# -*- coding: utf-8 -*-
"""Actividad 6 Lista

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qFUM-4yWwKavBSEg-OVcYd39D6dkmES
"""

temp = [80, 72, 95, 82, 79, 72, 85]

ntemp = []
for l in temp:
    ntemp.append(round((l - 32) * 5 / 9))

print(ntemp)