# -*- coding: utf-8 -*-
"""Programa 4 Objetos y decisiones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEcoGNEvkO5EFYoNa1ViLfReRPqLO98h
"""

class Calificaciones:
    def __init__(self):
        self.nombres = []
        self.calificaciones = []
        self.promedio_grupal = 0.0
        self.alumnos_destacados = []

    def leer_datos(self):
        print("Ingrese los nombres y calificaciones de 10 alumnos:")
        for i in range(10):
            nombre = input(f"Nombre del alumno {i+1}: ")
            calificacion = float(input(f"Calificación de {nombre}: "))
            self.nombres.append(nombre)
            self.calificaciones.append(calificacion)

    def realizar_proceso(self):
        if self.calificaciones:
            # Calcular el promedio grupal
            self.promedio_grupal = sum(self.calificaciones) / len(self.calificaciones)

            # Encontrar alumnos con calificación mayor a 9.5
            for i in range(len(self.calificaciones)):
                if self.calificaciones[i] > 9.5:
                    self.alumnos_destacados.append(self.nombres[i])

    def imprimir_resultados(self):
        print("\n--- Resultados del Grupo ---")
        print(f"Promedio grupal de calificación: {self.promedio_grupal:.2f}")

        print("\nAlumnos con calificación mayor a 9.5:")
        if self.alumnos_destacados:
            for alumno in self.alumnos_destacados:
                print(f"- {alumno}")
        else:
            print("No se encontraron alumnos con calificaciones superiores a 9.5.")

# --- Ejemplo de uso ---
if __name__ == "__main__":
    # Crear una instancia de la clase
    grupo_escolar = Calificaciones()

    # Llamar a los métodos en el orden correcto
    grupo_escolar.leer_datos()
    grupo_escolar.realizar_proceso()
    grupo_escolar.imprimir_resultados()