# -*- coding: utf-8 -*-
"""Programa 3 Creando un objeto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIOuYtdAZrO-rmOcD6xRLDrjD1wPDF-7
"""

class Triangulo:
    def __init__(self):
        self.base = 0.0
        self.altura = 0.0
        self.area = 0.0

    def recibir_mensajes(self):
        self.base = float(input("dame la base: "))
        self.altura = float(input("dame la altura: "))

    def calcular_area(self):
        self.area = (self.base * self.altura) / 2

    def imprimir_resultados(self):
        print(f"\nEl área del triángulo es: {self.area:.2f}")

mi_triangulo = Triangulo()
mi_triangulo.recibir_mensajes()
mi_triangulo.calcular_area()
mi_triangulo.imprimir_resultados()