# -*- coding: utf-8 -*-
"""Programa 5 Diccionario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjXDmLjPEIsz3Ek5YnK7_vXUufwcznUf
"""

diccionario = {
    "Nombre" : "Juan",
    "Matricula" : "231690263-0",
    "Edad" : "17",
    "Peso" : "56",
    "Telefono" : "311-452-1596",
    "Domicilio" : "Lomas",
    "Carrera" : "CDIA"
}
print(diccionario)

print(diccionario['Nombre'])

print(diccionario["Matricula"])

print(diccionario["Edad"])

print(diccionario['Peso'])

print(diccionario['Telefono'])

print(diccionario["Domicilio"])

print(diccionario["Carrera"])

diccionario['Nombre'] = "Jesus"
print(diccionario)

for x in diccionario:
  print(x)

for x in diccionario:
  print(diccionario[x])

for x, y in diccionario.items():
  print(x, y)

for list in diccionario:
  print(list)