# -*- coding: utf-8 -*-
"""Trabajo Alumno

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAUoLFKNhDZ7_CCGaOHLk7pAsijOYFk0
"""

class alumno():
  nombre = "Joseph"
  edad = 17
  peso = 67
  promedio = 8.9

  def inscripcion(self):
    print("El alumno se inscribio")

  def asesorias(self):
    print("El alumno asesoro")


Alumno=alumno()

print("El nombre del alumno: ",Alumno.nombre)
print("La edad del alumno es: ", Alumno.edad)
print("El peso del alumno es: ", Alumno.peso)
print("El promedio del alumno es: ", Alumno.promedio)

Alumno.inscripcion()
Alumno.asesorias()